name: Build and test

on:
  push:
    branches: [ master ]
    paths-ignore: &paths
    - "docs/**"
    - "settings.sample.yaml"
    - "README.md"
    - "LICENSE"
  pull_request:
    branches: [ master ]
    paths-ignore: *paths

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
